# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BricktradeApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BricktradeApp

  target 'BricktradeApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'BricktradeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'BricktradeApp-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for BricktradeApp-tvOS

#   target 'BricktradeApp-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
